[open]
prepend_rules = [
	{ url = "*.jpg", use = "openPic" },
	{ url = "*.png", use = "openPic" },
	{ url = "*.raw", use = "openPic" },
	{ url = "*.jpeg", use = "openPic" },
	{ mime = "text/*", use = "textEdit" },
	{ mime = "application/json", use = "textEdit" },
  { url = "*.docx", use = ["onlyoffice", "open"] },
  { url = "*.doc", use = ["onlyoffice", "open"] }
]

[opener]
openPic = [
	{ run = 'imv * -n "$@"', orphan = true, desc = "imv" }
]
textEdit = [
	{ run = 'nvim "$@"', block = true, desc = "Nvim" }
]
onlyoffice = [
  { run = 'onlyoffice-desktopeditors "$@"', orphan = true, desc = "OnlyOffice" },
]
play = [
	{ run = 'placeholder "$@"', orphan = true, desc = "Stremio" }
]

